apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: techdocs-sample
  description: Sample TechDocs documentation
  labels:
    backstage.io/techdocs-ref: url
spec:
  type: documentation
  lifecycle: experimental
  owner: user:default/user
  techdocs:
    source:
      type: github        # GitHub ソースから生成
      target_url: https://github.com/shouji-satou/TechDocTest001  # Markdown リポジトリ
